---
abstract: 'Infrastructure plugin for the Catalyst'
author:
  - 'Yuval Kogman, C<nothingmuch@woobling.org>'
build_requires:
  Class::MOP: 0
  ExtUtils::MakeMaker: 6.59
  Moose: 0
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Authentication
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::Session: 0.10
  Catalyst::Runtime: 0
  Class::Inspector: 0
  MRO::Compat: 0
  Moose: 0
  MooseX::Emulate::Class::Accessor::Fast: 0
  namespace::clean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/catagits/Catalyst-Plugin-Authentication.git
version: 0.10020
